Welcome to Step-by-Step TO our Manifesto:
----

The objective with this article is to elucidate and guide new ML engeniers, where just don't realize how to 
initiate the data proccess and wich model or data mining proccess choose.

In [22]:
import pandas as pd
import numpy as np
import csv as csv
import math
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, accuracy_score
from sklearn.cross_validation import train_test_split
import time
import time
from datetime import date
import datetime

%matplotlib inline

In [23]:
train_df = pd.read_csv('../hackerrank-predict-email-opens-dataset/training_dataset.csv/training_dataset.csv', header=0)  
train_df.head()

,user_id,mail_id,mail_category,mail_type,sent_time,open_time,click_time,unsubscribe_time,last_online,hacker_created_at,...,submissions_count_contest_1_days,submissions_count_contest_30_days,submissions_count_contest_365_days,submissions_count_contest_7_days,submissions_count_master,submissions_count_master_1_days,submissions_count_master_30_days,submissions_count_master_365_days,submissions_count_master_7_days,unsubscribed
0,AR+tMy3H/E+Re8Id20zUIz+amJkv6KU12o+BrgIDin0=,DQ/4I+GIOz2ZoIiK0Lg0AkwnI35XotghgUK/MYc101I=,mail_category_2,mail_type_1,1463497837,1.463541e+09,NaN,NaN,1.459520e+09,1432533023,...,0,0,0,0,13,0,0,13,0,False
1,1P4AOvdzJzhDSHi7jJ3udWv4ajpKxOn4T/rCLv4PrXU=,BL3z4RtiyfIDydaRYWX2ZXL6IX10QH1yG5ak1s/8Lls=,mail_category_1,mail_type_1,1461357640,NaN,NaN,NaN,1.461210e+09,1432184291,...,0,3,16,0,83,0,43,83,4,False
2,OEfFUcsTAGInCfsHuLZuIgdSNtuNsg8EdfN98VUZVTs=,BL3z4RtiyfIDydaRYWX2ZXL6IX10QH1yG5ak1s/8Lls=,mail_category_1,mail_type_1,1463499639,NaN,NaN,NaN,1.463411e+09,1433045937,...,0,0,0,0,16,0,3,16,0,False
3,1P4AOvdzJzhDSHi7jJ3udWv4ajpKxOn4T/rCLv4PrXU=,EHNBRbi6i9KO6cMHsuDPFjZVp2cY3RH+BiOKwPwzLQs=,mail_category_1,mail_type_1,1463182983,NaN,NaN,NaN,1.462768e+09,1432184291,...,0,0,16,0,85,0,9,85,0,False
4,CYRcuV0cR0algMZJ1N6+3uKcqi8iu+6tJNzmBbmgN7o=,K0y/NW59TJkYc5y0HUwDeAXrewYT0JQlkcozz0s2V5Q=,mail_category_4,mail_type_1,1461855019,NaN,NaN,NaN,1.461248e+09,1432998058,...,0,1,17,0,43,0,0,43,0,False

HOW GET MISSING DATA FOR EACH COLUMMNS
------

In [4]:
for cl in train_df.columns.values:
    value = train_df[cl].isnull().sum()
    if value>0:
        print cl, value

mail_category 425
mail_type 425
open_time 324701
click_time 458964
unsubscribe_time 484090
last_online 577
hacker_timezone 6939

HOW GET TYPES OF EACH COLUMMNS
------

In [4]:
for cl in train_df.columns.values:
    print cl,train_df[cl].dtype

user_id object
mail_id object
mail_category object
mail_type object
sent_time int64
open_time float64
click_time float64
unsubscribe_time float64
last_online float64
hacker_created_at int64
hacker_timezone float64
clicked bool
contest_login_count int64
contest_login_count_1_days int64
contest_login_count_30_days int64
contest_login_count_365_days int64
contest_login_count_7_days int64
contest_participation_count int64
contest_participation_count_1_days int64
contest_participation_count_30_days int64
contest_participation_count_365_days int64
contest_participation_count_7_days int64
forum_comments_count int64
forum_count int64
forum_expert_count int64
forum_questions_count int64
hacker_confirmation bool
ipn_count int64
ipn_count_1_days int64
ipn_count_30_days int64
ipn_count_365_days int64
ipn_count_7_days int64
ipn_read int64
ipn_read_1_days int64
ipn_read_30_days int64
ipn_read_365_days int64
ipn_read_7_days int64
opened bool
submissions_count int64
submissions_count_1_days int64
submissions_count_30_days int64
submissions_count_365_days int64
submissions_count_7_days int64
submissions_count_contest int64
submissions_count_contest_1_days int64
submissions_count_contest_30_days int64
submissions_count_contest_365_days int64
submissions_count_contest_7_days int64
submissions_count_master int64
submissions_count_master_1_days int64
submissions_count_master_30_days int64
submissions_count_master_365_days int64
submissions_count_master_7_days int64
unsubscribed bool

HOW CONVERT CATEGORICAL VALUES IN NUMERICAL
---------

#### GET HOW MANY CATEGORICAL VALUES IS AVAILABLE IN YOUR DATABASE

In [1]:
np.unique(train_df['mail_category'].values)

NameError: name 'np' is not defined

## 1 - GET DUMMIES

In [29]:
dummiesMail_category =  pd.get_dummies(train_df.mail_category,prefix='col')
dummiesMail_category.head()

,col_mail_category_1,col_mail_category_10,col_mail_category_11,col_mail_category_12,col_mail_category_13,col_mail_category_14,col_mail_category_15,col_mail_category_16,col_mail_category_17,col_mail_category_18,col_mail_category_2,col_mail_category_3,col_mail_category_4,col_mail_category_5,col_mail_category_6,col_mail_category_7,col_mail_category_8,col_mail_category_9
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

### Concate to original DataFrame

In [30]:
train_dfWithDummies = pd.concat([train_df, dummiesMail_category], axis=1)
train_dfWithDummies.head()

,user_id,mail_id,mail_category,mail_type,sent_time,open_time,click_time,unsubscribe_time,last_online,hacker_created_at,...,col_mail_category_17,col_mail_category_18,col_mail_category_2,col_mail_category_3,col_mail_category_4,col_mail_category_5,col_mail_category_6,col_mail_category_7,col_mail_category_8,col_mail_category_9
0,AR+tMy3H/E+Re8Id20zUIz+amJkv6KU12o+BrgIDin0=,DQ/4I+GIOz2ZoIiK0Lg0AkwnI35XotghgUK/MYc101I=,mail_category_2,mail_type_1,1463497837,1.463541e+09,NaN,NaN,1.459520e+09,1432533023,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1P4AOvdzJzhDSHi7jJ3udWv4ajpKxOn4T/rCLv4PrXU=,BL3z4RtiyfIDydaRYWX2ZXL6IX10QH1yG5ak1s/8Lls=,mail_category_1,mail_type_1,1461357640,NaN,NaN,NaN,1.461210e+09,1432184291,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,OEfFUcsTAGInCfsHuLZuIgdSNtuNsg8EdfN98VUZVTs=,BL3z4RtiyfIDydaRYWX2ZXL6IX10QH1yG5ak1s/8Lls=,mail_category_1,mail_type_1,1463499639,NaN,NaN,NaN,1.463411e+09,1433045937,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1P4AOvdzJzhDSHi7jJ3udWv4ajpKxOn4T/rCLv4PrXU=,EHNBRbi6i9KO6cMHsuDPFjZVp2cY3RH+BiOKwPwzLQs=,mail_category_1,mail_type_1,1463182983,NaN,NaN,NaN,1.462768e+09,1432184291,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,CYRcuV0cR0algMZJ1N6+3uKcqi8iu+6tJNzmBbmgN7o=,K0y/NW59TJkYc5y0HUwDeAXrewYT0JQlkcozz0s2V5Q=,mail_category_4,mail_type_1,1461855019,NaN,NaN,NaN,1.461248e+09,1432998058,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

**
When you need to group by an ID and a categorical Value forming a unique table with no reapeting element <br/>
the column 'Times' represent the number of times the ID and the categorical value shows
**

In [27]:
groupAndDummy = train_df.groupby(["user_id","mail_category"]).size().reset_index(name="Times")\
        .pivot(index='user_id', columns='mail_category', values='Times').reset_index()#.drop(["user_id"],axis=1)
# groupAndDummy.index.names = ["DummiesUniqueById"]
groupAndDummy.columns.name="DummiesUniqueById"
print groupAndDummy.shape
groupAndDummy.head()

(30535, 19)

DummiesUniqueById,user_id,mail_category_1,mail_category_10,mail_category_11,mail_category_12,mail_category_13,mail_category_14,mail_category_15,mail_category_16,mail_category_17,mail_category_18,mail_category_2,mail_category_3,mail_category_4,mail_category_5,mail_category_6,mail_category_7,mail_category_8,mail_category_9
0,++++AlrUVbE5PINY7DbtKaSSWKVBd1irRDUEQazAlB0=,4.0,1.0,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN,1.0,5.0,3.0,NaN,1.0,2.0,1.0,NaN
1,++E9b50RAFVUBx06HLYizCphGFSdewHiJ6O7R8dkb0w=,1.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,2.0,NaN,NaN
2,++VKdjPb2qYO+KV9T2r+wcFpg+Fz2B0ZlxO2KtCUQ24=,1.0,1.0,1.0,NaN,NaN,NaN,10.0,1.0,NaN,NaN,NaN,1.0,1.0,1.0,NaN,1.0,NaN,NaN
3,++Xam77eQwNSqOVgGAJufeNYduq3iqIRyvSuQATtoss=,11.0,1.0,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,6.0,4.0,NaN,NaN,1.0,NaN,NaN
4,++Zro4xLyeHDkcH0IrRRbpKek4twNACxWd40pdCM/rc=,10.0,1.0,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,5.0,2.0,NaN,1.0,1.0,NaN,1.0

## 2 - TRANSFORM INTO VALUE

In [39]:
dict_mail_category = dict([ (k,v) for v,k in enumerate(np.unique(train_df['mail_category'].values))])
dict_mail_category

{nan: 0,
 'mail_category_1': 1,
 'mail_category_10': 2,
 'mail_category_11': 3,
 'mail_category_12': 4,
 'mail_category_13': 5,
 'mail_category_14': 6,
 'mail_category_15': 7,
 'mail_category_16': 8,
 'mail_category_17': 9,
 'mail_category_18': 10,
 'mail_category_2': 11,
 'mail_category_3': 12,
 'mail_category_4': 13,
 'mail_category_5': 14,
 'mail_category_6': 15,
 'mail_category_7': 16,
 'mail_category_8': 17,
 'mail_category_9': 18}

In [41]:
train_df_mail_category_with_values = train_df['mail_category'].map(lambda x:dict_mail_category[x])
train_df_mail_category_with_values.head()

0    11
1     1
2     1
3     1
4    13
Name: mail_category, dtype: int64

### Alter the categorical to values into the main Data Frame

In [42]:
train_df['mail_category'] = train_df['mail_category'].map(lambda x:dict_mail_category[x])
train_df.head()

,user_id,mail_id,mail_category,mail_type,sent_time,open_time,click_time,unsubscribe_time,last_online,hacker_created_at,...,submissions_count_contest_1_days,submissions_count_contest_30_days,submissions_count_contest_365_days,submissions_count_contest_7_days,submissions_count_master,submissions_count_master_1_days,submissions_count_master_30_days,submissions_count_master_365_days,submissions_count_master_7_days,unsubscribed
0,AR+tMy3H/E+Re8Id20zUIz+amJkv6KU12o+BrgIDin0=,DQ/4I+GIOz2ZoIiK0Lg0AkwnI35XotghgUK/MYc101I=,11,mail_type_1,1463497837,1.463541e+09,NaN,NaN,1.459520e+09,1432533023,...,0,0,0,0,13,0,0,13,0,False
1,1P4AOvdzJzhDSHi7jJ3udWv4ajpKxOn4T/rCLv4PrXU=,BL3z4RtiyfIDydaRYWX2ZXL6IX10QH1yG5ak1s/8Lls=,1,mail_type_1,1461357640,NaN,NaN,NaN,1.461210e+09,1432184291,...,0,3,16,0,83,0,43,83,4,False
2,OEfFUcsTAGInCfsHuLZuIgdSNtuNsg8EdfN98VUZVTs=,BL3z4RtiyfIDydaRYWX2ZXL6IX10QH1yG5ak1s/8Lls=,1,mail_type_1,1463499639,NaN,NaN,NaN,1.463411e+09,1433045937,...,0,0,0,0,16,0,3,16,0,False
3,1P4AOvdzJzhDSHi7jJ3udWv4ajpKxOn4T/rCLv4PrXU=,EHNBRbi6i9KO6cMHsuDPFjZVp2cY3RH+BiOKwPwzLQs=,1,mail_type_1,1463182983,NaN,NaN,NaN,1.462768e+09,1432184291,...,0,0,16,0,85,0,9,85,0,False
4,CYRcuV0cR0algMZJ1N6+3uKcqi8iu+6tJNzmBbmgN7o=,K0y/NW59TJkYc5y0HUwDeAXrewYT0JQlkcozz0s2V5Q=,13,mail_type_1,1461855019,NaN,NaN,NaN,1.461248e+09,1432998058,...,0,1,17,0,43,0,0,43,0,False

Missing Values
---------

## 1 - Using the Mode value

In [45]:
mode_mail_type = train_df.mail_type.dropna().mode().values
mode_mail_type

array(['mail_type_1'], dtype=object)

### Substitution the na values to mode value

In [46]:
train_df.loc[ (train_df.mail_type.isnull()), 'mail_type'] = mode_mail_type
train_df.mail_type.isnull().sum()

0

## 2 - Using the Mean value

In [56]:
mean_mail_category = train_df.mail_category.dropna().mean()
mean_mail_category

7.551484627032721

In [57]:
train_df.loc[ (train_df.mail_category==0), 'mail_category'] = mean_mail_category
train_df.mail_category.isnull().sum()

0

Dropping Colummns
----------

In [59]:
train_df = train_df.drop(['user_id','mail_id'], axis=1) 
train_df.head()

,mail_category,mail_type,sent_time,open_time,click_time,unsubscribe_time,last_online,hacker_created_at,hacker_timezone,clicked,...,submissions_count_contest_1_days,submissions_count_contest_30_days,submissions_count_contest_365_days,submissions_count_contest_7_days,submissions_count_master,submissions_count_master_1_days,submissions_count_master_30_days,submissions_count_master_365_days,submissions_count_master_7_days,unsubscribed
0,11.0,mail_type_1,1463497837,1.463541e+09,NaN,NaN,1.459520e+09,1432533023,18000.0,False,...,0,0,0,0,13,0,0,13,0,False
1,1.0,mail_type_1,1461357640,NaN,NaN,NaN,1.461210e+09,1432184291,-25200.0,False,...,0,3,16,0,83,0,43,83,4,False
2,1.0,mail_type_1,1463499639,NaN,NaN,NaN,1.463411e+09,1433045937,18000.0,False,...,0,0,0,0,16,0,3,16,0,False
3,1.0,mail_type_1,1463182983,NaN,NaN,NaN,1.462768e+09,1432184291,-25200.0,False,...,0,0,16,0,85,0,9,85,0,False
4,13.0,mail_type_1,1461855019,NaN,NaN,NaN,1.461248e+09,1432998058,18000.0,False,...,0,1,17,0,43,0,0,43,0,False

Working with Dates if date a timestamp
--------------

### 1 - Get the Year

In [89]:
last_online_year = train_df['last_online'].head().map(lambda x:time.strftime('%Y', time.localtime(x)))
last_online_year.head()

0    2016
1    2016
2    2016
3    2016
4    2016
Name: last_online, dtype: object

### 2 - Get the Month

In [90]:
last_online_month = train_df['last_online'].head().map(lambda x:time.strftime('%m', time.localtime(x)))
last_online_month.head()

0    04
1    04
2    05
3    05
4    04
Name: last_online, dtype: object

### 3 - Get the Day

In [92]:
last_online_day = train_df['last_online'].head().map(lambda x:time.strftime('%d', time.localtime(x)))
last_online_day.head()

0    01
1    21
2    16
3    09
4    21
Name: last_online, dtype: object

### 4 - Count the number of day by now

In [94]:
last_online_counts_day = train_df['last_online'].head().map(lambda x:(datetime.datetime.today()-datetime.datetime.fromtimestamp(x)).days)
last_online_counts_day.head()

0    160
1    140
2    115
3    122
4    140
Name: last_online, dtype: int64

Convert to int64 or int32 or int18
-----------

In [95]:
last_online_day = train_df['last_online'].head().map(lambda x:time.strftime('%d', time.localtime(x))).astype(int)
last_online_day.head()

0     1
1    21
2    16
3     9
4    21
Name: last_online, dtype: int32

How Drop rows with NULL Values (missing values)
-----------

In [103]:
train_df = pd.read_csv('../hackerrank-predict-email-opens-dataset/training_dataset.csv/training_dataset.csv', header=0)  
print train_df.shape
for cl in train_df.columns.values:
    value = train_df[cl].isnull().sum()
    if value>0:
        print cl, value

(486048, 54)
mail_category 425
mail_type 425
open_time 324701
click_time 458964
unsubscribe_time 484090
last_online 577
hacker_timezone 6939

In [104]:
train_df = train_df.dropna(subset=['mail_category','mail_type','last_online','hacker_timezone'])
train_df.shape

(478192, 54)

In [105]:
for cl in train_df.columns.values:
    value = train_df[cl].isnull().sum()
    if value>0:
        print cl, value

open_time 319365
click_time 451565
unsubscribe_time 476279

Convert Boolean to int
--------

In [111]:
last_opened = train_df['opened'].map({True:1,False:0})
train_df['opened'] = last_opened
train_df['opened'].head()

0    1
1    0
2    0
3    0
4    0
Name: opened, dtype: int64

Sort All the variables to model constancy
---------

In [112]:
train_df = train_df.reindex_axis(sorted(train_df.columns), axis=1)
train_df.head()

,click_time,clicked,contest_login_count,contest_login_count_1_days,contest_login_count_30_days,contest_login_count_365_days,contest_login_count_7_days,contest_participation_count,contest_participation_count_1_days,contest_participation_count_30_days,...,submissions_count_contest_365_days,submissions_count_contest_7_days,submissions_count_master,submissions_count_master_1_days,submissions_count_master_30_days,submissions_count_master_365_days,submissions_count_master_7_days,unsubscribe_time,unsubscribed,user_id
0,NaN,False,1,0,0,1,0,1,0,0,...,0,0,13,0,0,13,0,NaN,False,AR+tMy3H/E+Re8Id20zUIz+amJkv6KU12o+BrgIDin0=
1,NaN,False,3,0,1,3,0,3,0,1,...,16,0,83,0,43,83,4,NaN,False,1P4AOvdzJzhDSHi7jJ3udWv4ajpKxOn4T/rCLv4PrXU=
2,NaN,False,3,0,0,3,0,3,0,0,...,0,0,16,0,3,16,0,NaN,False,OEfFUcsTAGInCfsHuLZuIgdSNtuNsg8EdfN98VUZVTs=
3,NaN,False,3,0,0,3,0,3,0,0,...,16,0,85,0,9,85,0,NaN,False,1P4AOvdzJzhDSHi7jJ3udWv4ajpKxOn4T/rCLv4PrXU=
4,NaN,False,5,0,0,5,0,13,0,0,...,17,0,43,0,0,43,0,NaN,False,CYRcuV0cR0algMZJ1N6+3uKcqi8iu+6tJNzmBbmgN7o=

#### make target variable first after order

In [113]:
train_df = train_df.reindex_axis(['opened'] + list([col for col in train_df.columns if col != 'opened']), axis=1)
train_df.head()

,opened,click_time,clicked,contest_login_count,contest_login_count_1_days,contest_login_count_30_days,contest_login_count_365_days,contest_login_count_7_days,contest_participation_count,contest_participation_count_1_days,...,submissions_count_contest_365_days,submissions_count_contest_7_days,submissions_count_master,submissions_count_master_1_days,submissions_count_master_30_days,submissions_count_master_365_days,submissions_count_master_7_days,unsubscribe_time,unsubscribed,user_id
0,1,NaN,False,1,0,0,1,0,1,0,...,0,0,13,0,0,13,0,NaN,False,AR+tMy3H/E+Re8Id20zUIz+amJkv6KU12o+BrgIDin0=
1,0,NaN,False,3,0,1,3,0,3,0,...,16,0,83,0,43,83,4,NaN,False,1P4AOvdzJzhDSHi7jJ3udWv4ajpKxOn4T/rCLv4PrXU=
2,0,NaN,False,3,0,0,3,0,3,0,...,0,0,16,0,3,16,0,NaN,False,OEfFUcsTAGInCfsHuLZuIgdSNtuNsg8EdfN98VUZVTs=
3,0,NaN,False,3,0,0,3,0,3,0,...,16,0,85,0,9,85,0,NaN,False,1P4AOvdzJzhDSHi7jJ3udWv4ajpKxOn4T/rCLv4PrXU=
4,0,NaN,False,5,0,0,5,0,13,0,...,17,0,43,0,0,43,0,NaN,False,CYRcuV0cR0algMZJ1N6+3uKcqi8iu+6tJNzmBbmgN7o=

Normalize the data
---------

In [8]:
cols_to_norm = ['contest_login_count']
mean_ = train_df.contest_login_count.mean()
max_ = train_df.contest_login_count.max()
min_ = train_df.contest_login_count.min()
train_df[cols_to_norm] = train_df[cols_to_norm].apply(lambda x: (x - x.mean()) / (x.max() - x.min()))
train_df[cols_to_norm].head()

   contest_login_count
0            -0.021922
1            -0.005661
2            -0.005661
3            -0.005661
4             0.010599

Create columns with zeros
--------

In [9]:
dataframetest = pd.DataFrame({'mail_category':['mail_category_1', 'mail_category_10', 'mail_category_11',
       'mail_category_12']})
dataframetest.head()

      mail_category
0   mail_category_1
1  mail_category_10
2  mail_category_11
3  mail_category_12

In [18]:
all_mail_categories = ['mail_category_1', 'mail_category_10', 'mail_category_11',
       'mail_category_12', 'mail_category_13', 'mail_category_14',
       'mail_category_15', 'mail_category_16', 'mail_category_17',
       'mail_category_18', 'mail_category_2', 'mail_category_3',
       'mail_category_4', 'mail_category_5', 'mail_category_6',
       'mail_category_7', 'mail_category_8', 'mail_category_9']


dataFrameMailCategoryDiff = np.setdiff1d(all_mail_categories,np.unique(dataframetest.mail_category)) 
print 'Difference columns not found on dataframe: ',dataFrameMailCategoryDiff
dummiesMail_category =  pd.get_dummies(dataframetest.mail_category,prefix='col')
dataframetest = pd.concat([dataframetest, dummiesMail_category], axis=1)
dataframetest = dataframetest.drop(['mail_category'],axis=1) #drop the mail_category
dataframetest.head()

Difference columns not found on dataframe:  ['mail_category_13' 'mail_category_14' 'mail_category_15'
 'mail_category_16' 'mail_category_17' 'mail_category_18' 'mail_category_2'
 'mail_category_3' 'mail_category_4' 'mail_category_5' 'mail_category_6'
 'mail_category_7' 'mail_category_8' 'mail_category_9']

,col_mail_category_1,col_mail_category_10,col_mail_category_11,col_mail_category_12,col_mail_category_1,col_mail_category_10,col_mail_category_11,col_mail_category_12,col_mail_category_1,col_mail_category_10,col_mail_category_11,col_mail_category_12
0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

#### Now we concatenate the other dummies not found on the dataframe

In [19]:
for mailCategoryItem in map(lambda x:"col_"+x,dataFrameMailCategoryDiff):
    dataframetest = pd.concat([dataframetest,pd.DataFrame({mailCategoryItem: np.zeros(dataframetest.shape[0])})],axis=1)
dataframetest.head()

,col_mail_category_1,col_mail_category_10,col_mail_category_11,col_mail_category_12,col_mail_category_1,col_mail_category_10,col_mail_category_11,col_mail_category_12,col_mail_category_1,col_mail_category_10,...,col_mail_category_17,col_mail_category_18,col_mail_category_2,col_mail_category_3,col_mail_category_4,col_mail_category_5,col_mail_category_6,col_mail_category_7,col_mail_category_8,col_mail_category_9
0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Creating bins with Columns
---------------

#### Auto bins creations

In [40]:
train_df = pd.read_csv('../hackerrank-predict-email-opens-dataset/training_dataset.csv/training_dataset.csv', header=0)

In [41]:
dataTemp  = train_df['submissions_count'].value_counts()
hist, edges = np.histogram(dataTemp, bins=10)
print hist
print edges
dataTempDict = dataTemp.to_dict()
train_df['submissions_count'] = train_df['submissions_count'].map(lambda x: [i for i,v in enumerate(edges) if v<=dataTempDict[x]][-1] )
dummies_submissions_count =  pd.get_dummies(train_df.submissions_count,prefix='submissions_count')
train_df = pd.concat([train_df, dummies_submissions_count], axis=1)
train_df.head()

[1080   12    3    1    0    0    0    0    0    1]
[  1.00000000e+00   6.07270000e+03   1.21444000e+04   1.82161000e+04
   2.42878000e+04   3.03595000e+04   3.64312000e+04   4.25029000e+04
   4.85746000e+04   5.46463000e+04   6.07180000e+04]

,user_id,mail_id,mail_category,mail_type,sent_time,open_time,click_time,unsubscribe_time,last_online,hacker_created_at,...,submissions_count_master_1_days,submissions_count_master_30_days,submissions_count_master_365_days,submissions_count_master_7_days,unsubscribed,submissions_count_0,submissions_count_1,submissions_count_2,submissions_count_3,submissions_count_10
0,AR+tMy3H/E+Re8Id20zUIz+amJkv6KU12o+BrgIDin0=,DQ/4I+GIOz2ZoIiK0Lg0AkwnI35XotghgUK/MYc101I=,mail_category_2,mail_type_1,1463497837,1.463541e+09,NaN,NaN,1.459520e+09,1432533023,...,0,0,13,0,False,0.0,1.0,0.0,0.0,0.0
1,1P4AOvdzJzhDSHi7jJ3udWv4ajpKxOn4T/rCLv4PrXU=,BL3z4RtiyfIDydaRYWX2ZXL6IX10QH1yG5ak1s/8Lls=,mail_category_1,mail_type_1,1461357640,NaN,NaN,NaN,1.461210e+09,1432184291,...,0,43,83,4,False,1.0,0.0,0.0,0.0,0.0
2,OEfFUcsTAGInCfsHuLZuIgdSNtuNsg8EdfN98VUZVTs=,BL3z4RtiyfIDydaRYWX2ZXL6IX10QH1yG5ak1s/8Lls=,mail_category_1,mail_type_1,1463499639,NaN,NaN,NaN,1.463411e+09,1433045937,...,0,3,16,0,False,0.0,1.0,0.0,0.0,0.0
3,1P4AOvdzJzhDSHi7jJ3udWv4ajpKxOn4T/rCLv4PrXU=,EHNBRbi6i9KO6cMHsuDPFjZVp2cY3RH+BiOKwPwzLQs=,mail_category_1,mail_type_1,1463182983,NaN,NaN,NaN,1.462768e+09,1432184291,...,0,9,85,0,False,1.0,0.0,0.0,0.0,0.0
4,CYRcuV0cR0algMZJ1N6+3uKcqi8iu+6tJNzmBbmgN7o=,K0y/NW59TJkYc5y0HUwDeAXrewYT0JQlkcozz0s2V5Q=,mail_category_4,mail_type_1,1461855019,NaN,NaN,NaN,1.461248e+09,1432998058,...,0,0,43,0,False,1.0,0.0,0.0,0.0,0.0

##### passing the bin edges to the histogram creation

In [42]:
train_df = pd.read_csv('../hackerrank-predict-email-opens-dataset/training_dataset.csv/training_dataset.csv', header=0)

In [44]:
dataTemp  = train_df['submissions_count'].value_counts()
hist, edges = np.histogram(dataTemp, bins=[1.00000000e+00 ,22768.,46786.8,70805.6,94824.4,
                                           118843.2,142862.,166880.8,190899.6,
                                           214918.4,238937.2,262956.])
print hist
print edges
dataTempDict = dataTemp.to_dict()
train_df['submissions_count'] = train_df['submissions_count'].map(lambda x: [i for i,v in enumerate(edges) if v<=dataTempDict[x]][-1] )
dummies_submissions_count =  pd.get_dummies(train_df.submissions_count,prefix='submissions_count')
train_df = pd.concat([train_df, dummies_submissions_count], axis=1)
train_df.head()

[0 1 1 0 0 0 0 0 0 0 0]
[  1.00000000e+00   2.27680000e+04   4.67868000e+04   7.08056000e+04
   9.48244000e+04   1.18843200e+05   1.42862000e+05   1.66880800e+05
   1.90899600e+05   2.14918400e+05   2.38937200e+05   2.62956000e+05]

,user_id,mail_id,mail_category,mail_type,sent_time,open_time,click_time,unsubscribe_time,last_online,hacker_created_at,...,submissions_count_master_30_days,submissions_count_master_365_days,submissions_count_master_7_days,unsubscribed,submissions_count_0,submissions_count_1,submissions_count_2,submissions_count_1,submissions_count_2,submissions_count_11
0,AR+tMy3H/E+Re8Id20zUIz+amJkv6KU12o+BrgIDin0=,DQ/4I+GIOz2ZoIiK0Lg0AkwnI35XotghgUK/MYc101I=,mail_category_2,mail_type_1,1463497837,1.463541e+09,NaN,NaN,1.459520e+09,1432533023,...,0,13,0,False,1.0,0.0,0.0,0.0,0.0,1.0
1,1P4AOvdzJzhDSHi7jJ3udWv4ajpKxOn4T/rCLv4PrXU=,BL3z4RtiyfIDydaRYWX2ZXL6IX10QH1yG5ak1s/8Lls=,mail_category_1,mail_type_1,1461357640,NaN,NaN,NaN,1.461210e+09,1432184291,...,43,83,4,False,1.0,0.0,0.0,0.0,0.0,1.0
2,OEfFUcsTAGInCfsHuLZuIgdSNtuNsg8EdfN98VUZVTs=,BL3z4RtiyfIDydaRYWX2ZXL6IX10QH1yG5ak1s/8Lls=,mail_category_1,mail_type_1,1463499639,NaN,NaN,NaN,1.463411e+09,1433045937,...,3,16,0,False,1.0,0.0,0.0,0.0,0.0,1.0
3,1P4AOvdzJzhDSHi7jJ3udWv4ajpKxOn4T/rCLv4PrXU=,EHNBRbi6i9KO6cMHsuDPFjZVp2cY3RH+BiOKwPwzLQs=,mail_category_1,mail_type_1,1463182983,NaN,NaN,NaN,1.462768e+09,1432184291,...,9,85,0,False,1.0,0.0,0.0,0.0,0.0,1.0
4,CYRcuV0cR0algMZJ1N6+3uKcqi8iu+6tJNzmBbmgN7o=,K0y/NW59TJkYc5y0HUwDeAXrewYT0JQlkcozz0s2V5Q=,mail_category_4,mail_type_1,1461855019,NaN,NaN,NaN,1.461248e+09,1432998058,...,0,43,0,False,1.0,0.0,0.0,0.0,0.0,1.0

Fill NA or Null values with some value
----------

In [45]:
train_df = train_df.fillna(0)
train_df.head()

,user_id,mail_id,mail_category,mail_type,sent_time,open_time,click_time,unsubscribe_time,last_online,hacker_created_at,...,submissions_count_master_30_days,submissions_count_master_365_days,submissions_count_master_7_days,unsubscribed,submissions_count_0,submissions_count_1,submissions_count_2,submissions_count_1,submissions_count_2,submissions_count_11
0,AR+tMy3H/E+Re8Id20zUIz+amJkv6KU12o+BrgIDin0=,DQ/4I+GIOz2ZoIiK0Lg0AkwnI35XotghgUK/MYc101I=,mail_category_2,mail_type_1,1463497837,1.463541e+09,0.0,0.0,1.459520e+09,1432533023,...,0,13,0,False,1.0,0.0,0.0,0.0,0.0,1.0
1,1P4AOvdzJzhDSHi7jJ3udWv4ajpKxOn4T/rCLv4PrXU=,BL3z4RtiyfIDydaRYWX2ZXL6IX10QH1yG5ak1s/8Lls=,mail_category_1,mail_type_1,1461357640,0.000000e+00,0.0,0.0,1.461210e+09,1432184291,...,43,83,4,False,1.0,0.0,0.0,0.0,0.0,1.0
2,OEfFUcsTAGInCfsHuLZuIgdSNtuNsg8EdfN98VUZVTs=,BL3z4RtiyfIDydaRYWX2ZXL6IX10QH1yG5ak1s/8Lls=,mail_category_1,mail_type_1,1463499639,0.000000e+00,0.0,0.0,1.463411e+09,1433045937,...,3,16,0,False,1.0,0.0,0.0,0.0,0.0,1.0
3,1P4AOvdzJzhDSHi7jJ3udWv4ajpKxOn4T/rCLv4PrXU=,EHNBRbi6i9KO6cMHsuDPFjZVp2cY3RH+BiOKwPwzLQs=,mail_category_1,mail_type_1,1463182983,0.000000e+00,0.0,0.0,1.462768e+09,1432184291,...,9,85,0,False,1.0,0.0,0.0,0.0,0.0,1.0
4,CYRcuV0cR0algMZJ1N6+3uKcqi8iu+6tJNzmBbmgN7o=,K0y/NW59TJkYc5y0HUwDeAXrewYT0JQlkcozz0s2V5Q=,mail_category_4,mail_type_1,1461855019,0.000000e+00,0.0,0.0,1.461248e+09,1432998058,...,0,43,0,False,1.0,0.0,0.0,0.0,0.0,1.0

Merge Tables By Some Value
--------------

In [ ]:
# result = pd.merge(submissionsPre, challenges, on=['challenge_id'])



1. Identifying the source information
2. Picking the data points that need to be analyzed
3. Extracting the relevant information from the data
4. Identifying the key values from the extracted data set
5. Interpreting and reporting the results
 
There are various steps that are involved in mining data as shown in the picture.

1. Data Integration: First of all the data are collected and integrated from all the different sources.
2. Data Selection: We may not all the data we have collected in the first step. So in this step we select only those data which we think useful for data mining.
3. Data Cleaning: The data we have collected are not clean and may contain errors, missing values, noisy or inconsistent data. So we need to apply different techniques to get rid of such anomalies.
4. Data Transformation: The data even after cleaning are not ready for mining as we need to transform them into forms appropriate for mining. The techniques used to accomplish this are smoothing, aggregation, normalization etc.
5. Data Mining: Now we are ready to apply data mining techniques on the data to discover the interesting patterns. Techniques like clustering and association analysis are among the many different techniques used for data mining.
6. Pattern Evaluation and Knowledge Presentation: This step involves visualization, transformation, removing redundant patterns etc from the patterns we generated.
7. Decisions / Use of Discovered Knowledge: This step helps user to make use of the knowledge acquired to take better decisions.